"""

Revision ID: 10075ef4eb2d
Revises: 7239c1087f1d
Create Date: 2024-09-26 13:46:14.671673

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10075ef4eb2d"
down_revision = "7239c1087f1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
