"""Login

Revision ID: 7239c1087f1d
Revises: 0667bbc320f2
Create Date: 2024-09-22 16:56:30.697762

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7239c1087f1d"
down_revision = "0667bbc320f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
