"""add_roles

Revision ID: 91e634d0eacc
Revises: f505c33a8bd6
Create Date: 2024-10-01 11:48:05.356324

"""
import flask_authorize
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '91e634d0eacc'
down_revision = 'f505c33a8bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = op.create_table('role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowances', flask_authorize.mixins.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )

    op.bulk_insert(role, [
        {"name": "user", "allowances": {"artist": "r", "release": "r", "collection": "r"}},
        {"name": "admin", "allowances": {}}
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
