services:
  app-test:
    build:
      context: .
    container_name: self-improvement-test
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./app:/app
    environment:
      - PG_USER=postgres
      - PG_HOST=db-test
      - PG_PASS=postgres
      - PG_PORT=5432
      - PG_DATABASE=db-test
      - ENVIRONMENT=local
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db-test/db-test
      - SECRET_KEY=topkek
    networks:
      test-flask-network:
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: postgres:14.5
    container_name: db-test
    networks:
      test-flask-network:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-test
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 3

networks:
  test-flask-network:
    driver: bridge
