services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: self-improvement-app
    networks:
      - flask-network
    depends_on:
      - db
    environment:
      - PG_USER=postgres
      - PG_HOST=db
      - PG_PASS=postgres
      - PG_PORT=5432
      - PG_DATABASE=db
      - ENVIRONMENT=local
    env_file:
      - .docker-env
    ports:
      - "5005:8000"
    volumes:
      - ./app:/app

  db:
    image: postgres:14.5
    container_name: db
    networks:
      - flask-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5534:5432"
    volumes:
       - ./db_data:/var/lib/postgresql

  adminer:
    image: adminer
    networks:
      - flask-network
    restart: always
    ports:
      - 8080:8080

networks:
  flask-network:
    driver: bridge
